version: "3"
services:
  backend:
    build: .
    ports:
      - "6565:6565"
  proxy:
    image: envoyproxy/envoy:distroless-v1.27-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
