version: "3"
services:
  proxy:
    image: envoyproxy/envoy:distroless-v1.27-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./src/main/resources/sample.sql:/docker-entrypoint-initdb.d/01_data.sql
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wedding_kanshasai
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: Asia/Tokyo
    restart: always
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    restart: always
