CREATE TABLE IF NOT EXISTS
  events (
    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS
  sessions (
    id BINARY(16) NOT NULL PRIMARY KEY,
    event_id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    state_id INTEGER NOT NULL DEFAULT 1,
    cover_screen_id INTEGER NULL,
    current_quiz_id BINARY(16) NULL,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS
  quizzes (
    id BINARY(16) NOT NULL PRIMARY KEY,
    event_id BINARY(16) NOT NULL,
    body VARCHAR(100) NOT NULL,
    correct_answer TEXT NOT NULL,
    type INTEGER NOT NULL DEFAUlT 0,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS
  participants (
    id BINARY(16) NOT NULL PRIMARY KEY,
    session_id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    image_id BINARY(16) NULL,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

ALTER TABLE sessions ADD FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE quizzes ADD FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE participants ADD FOREIGN KEY (session_id) REFERENCES sessions(id);
