CREATE TABLE IF NOT EXISTS
  events (
    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );
