CREATE TABLE IF NOT EXISTS
  events (
    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

CREATE TABLE IF NOT EXISTS
  sessions (
    id BINARY(16) NOT NULL PRIMARY KEY,
    event_id BINARY(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    progress_id INTEGER NOT NULL DEFAULT 1,
    cover_screen_id INTEGER NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAUlT false,
    created_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAUlT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );

ALTER TABLE sessions ADD FOREIGN KEY (event_id) REFERENCES events(id);

