blank_issues_enabled: false
contact_links:
  - name: Create issue
    url: https://github.com/WeddingCamp/wedding-kanshasai-protobuf/issues/new?assignees=mizucoffee&labels=&milestone=Sprint1&projects=WeddingCamp/1
    about: Issue template with pre-entered parameters
