name: "[nightly] CD"
on:
  push:
    branches:
      - 'develop'
jobs:
  build-and-push:
    uses: ./.github/workflows/publish.yml
    with:
      environment: nightly
    secrets:
      DOCKERHUB_REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
