name: "[CD] Publish"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: stg
        type: choice
        options:
          - nightly
          - stg
          - prd
env:
  environment: ${{ inputs.environment || 'stg' }}
jobs:
  test:
    uses: ./.github/workflows/ci-tests.yml

  build-and-push:
    runs-on:
      - self-hosted
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_REGISTRY }}/library/wedding-kanshasai-backend-${{ env.environment }}:${{ github.sha }},${{ secrets.DOCKERHUB_REGISTRY }}/library/wedding-kanshasai-backend-${{ env.environment }}:latest

      - name: Apply new image
        shell: bash
        run: |
          curl ${{ secrets.DEPLOY_URL }}?env=${{ env.environment }}
